### Web에서 생존 여부 예측

In [1]:
from custom_utils import *
import os

In [2]:
## 저장경로
SAVE_PATH= r'C:\Users\KDP-43\Desktop\DL_web\models\Adam\alive_1'

# 저장 파일명
SAVE_MODEL = SAVE_PATH+'\model_all.pth'

In [3]:
SAVE_MODEL

'C:\\Users\\KDP-43\\Desktop\\DL_web\\models\\Adam\\alive_1\\model_all.pth'

In [4]:
if os.path.exists(SAVE_MODEL):
	SepsisLODModel= torch.load(SAVE_MODEL, weights_only=False)
	print("경로상 파일이 존재합니다.")
else:
	print(f'{SAVE_MODEL} 파일이 존재하지 않습니다. 다시 확인하세요.')

경로상 파일이 존재합니다.


In [5]:
summary(SepsisLODModel)

Layer (type:depth-idx)                   Param #
SepsisLODModel                           --
├─Linear: 1-1                            400
├─ModuleList: 1-2                        --
│    └─Linear: 2-1                       50,500
│    └─Linear: 2-2                       125,250
│    └─Linear: 2-3                       12,550
├─Linear: 1-3                            51
Total params: 188,751
Trainable params: 188,751
Non-trainable params: 0

예측 <hr>

In [6]:
data_input = [80, "여자", 0]

# 입력 데이터 적합성 확인-----------------------------------------------------------
if len(data_input) !=3: print("나이, 성별, 발병 횟수 순으로 다시 입력하세요.")

# 

# input data 성별 전처리
gender_dict = {"남자":0,"남":0,"남성":0, "여자":1,"여":1,"여성":1}
## 성별 적합성 확인
if data_input[1] not in list(gender_dict.keys()): 
    print("성별은 [남,여] [남성,여성] [남자,여자]만 가능합니다.")

data_input[1] = gender_dict[data_input[1]]
print(data_input)

# 텐서화
dataTS = torch.FloatTensor(data_input).reshape(1,-1)
print(dataTS, dataTS.shape)

# test data 예측
weights=0.9

SepsisLODModel.eval()
with torch.no_grad():
    pre_test = SepsisLODModel(dataTS)
    
print("이진 분류 사망(1) 확률:", pre_test)
print("이진 분류 생존(0) 확률:", 1-pre_test)
print()
print(pre_test > weights)
print((pre_test >weights).item())

result ='생존' if (pre_test > weights).item() else '사망'
print(result)

[80, 1, 0]
tensor([[80.,  1.,  0.]]) torch.Size([1, 3])
이진 분류 사망(1) 확률: tensor([[0.8309]])
이진 분류 생존(0) 확률: tensor([[0.1691]])

tensor([[False]])
False
사망


In [10]:
import joblib      # AI 모델 관련
import torch

In [15]:
def detectLang(data_input):
	

    result=""
    # gender_dict = {"남자":0,"남":0,"남성":0, "여자":1,"여":1,"여성":1}

    if len(data_input) !=3: 
		
        result ="나이, 성별, 발병 횟수 순으로 다시 입력하세요."

	# input data 성별 전처리
	## 성별 적합성 확인
    if data_input[1] not in list(gender_dict.keys()): 
        result="성별은 [남,여] [남성,여성] [남자,여자]만 가능합니다."

    data_input[1] = gender_dict[data_input[1]]
    # print(data_input)

    data_input = list(map(int, data_input))

    # 텐서화
    dataTS = torch.FloatTensor(data_input).reshape(1,-1)
    print(dataTS, dataTS.shape)

    # test data 예측-----------------------------------------
    # 모델 로드
    # pklfile = r'C:\Users\KDP-43\Desktop\DL_project\cgi-bin\model\alive_1\model_all.pth'

    # SepsisModel = joblib.load(pklfile)


    SepsisLODModel.eval()
    with torch.no_grad():
        pre_test = SepsisLODModel(dataTS)
        
    print(pre_test)
    result ="생존" if (pre_test > 0.88).item() else "사망"

    return result

In [16]:
aaa = detectLang(['26','남자','1'])
aaas

tensor([[26.,  0.,  1.]]) torch.Size([1, 3])
tensor([[0.8946]])


'생존'

In [17]:
aaa = detectLang(['78','여자','1'])
aaa

tensor([[78.,  1.,  1.]]) torch.Size([1, 3])
tensor([[0.8782]])


'사망'